

course=["C","C++","Java","C#","Android","Algorithm","Data Structure","Python","Java","Java"]
#print(course)
#print(len(course))
#course.append("Data Mining")
#print(course)
#course.insert(4,"OS")
#print(course)
#course.remove("C#")
#print(course)
#course.sort()
#print(course)
#course.reverse()
#print(course)
#course.pop()
#course.pop()
#print(course)
#course.clear()
#print(course)
#course2=course.copy()
#print(course2)
#pos=course.index("Algorithm")
#print(pos)
#pos=course.count("Android")
#print(pos)